name: Compilar LaTeX y Desplegar PDF

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar codigo fuente
        uses: actions/checkout@v4

      - name: Compilar documento LaTeX
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex
          args: "-pdf -bibtex -interaction=nonstopmode"

      - name: Desplegar PDF en GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          destination_dir: .
          PUBLISH_BRANCH: gh-pages
          keep_files: false
          allow_empty_commit: true
